/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(OFDM_Estimator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c9df6e56712b32e764800a68cb2ab1d6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/OFDM_Estimator/OFDM_Estimator.h>
// pydoc.h is automatically generated in the build directory
#include <OFDM_Estimator_pydoc.h>

void bind_OFDM_Estimator(py::module& m)
{

    using OFDM_Estimator    = ::gr::OFDM_Estimator::OFDM_Estimator;


    py::class_<OFDM_Estimator, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<OFDM_Estimator>>(m, "OFDM_Estimator", D(OFDM_Estimator))

        .def(py::init(&OFDM_Estimator::make),
           py::arg("samp_rate"),
           py::arg("signal"),
           py::arg("min_items"),
           py::arg("typ_len"),
           py::arg("typ_cp"),
           D(OFDM_Estimator,make)
        )
        




        
        .def("set_samp_rate",&OFDM_Estimator::set_samp_rate,       
            py::arg("d_samp_rate"),
            D(OFDM_Estimator,set_samp_rate)
        )

        ;




}








