/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-OFDM_Estimator
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_OFDM_ESTIMATOR_API_H
#define INCLUDED_OFDM_ESTIMATOR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_OFDM_Estimator_EXPORTS
#define OFDM_ESTIMATOR_API __GR_ATTR_EXPORT
#else
#define OFDM_ESTIMATOR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_OFDM_ESTIMATOR_API_H */
